runes:
  sakura_blessing:
    display_name: "&d❀ Sakura Blessing"
    rarity: "MYTHIC"
    type: "BOW"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"
  sakura_blessing_2:
    display_name: "&d❀ Sakura Blessing 2"
    rarity: "MYTHIC"
    type: "CHESTPLATE"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"
  sakura_blessing_3:
    display_name: "&d❀ Sakura Blessing 3"
    rarity: "MYTHIC"
    type: "BOOTS"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"
  sakura_blessing_4:
    display_name: "&d❀ Sakura Blessing 4"
    rarity: "MYTHIC"
    type: "HELMET"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"
  sakura_blessing_5:
    display_name: "&d❀ Sakura Blessing 4"
    rarity: "MYTHIC"
    type: "PICKAXE"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"
  sakura_blessing_6:
    display_name: "&d❀ Sakura Blessing 4"
    rarity: "MYTHIC"
    type: "SWORD"
    particle: "FLAME"
    head_skin: "https://textures.minecraft.net/texture/82090aa835f6b97eea8dad4309e96e6c85e727749a24fb7362af79c4d57f3e89"
    lore:
      - "&7Sakura petals will fall at your will!"
      - ""
      - "&7Apply this blessing to a chestplate!"